# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import docusign_esign
from docusign_esign.rest import ApiException
from docusign_esign.apis.folders_api import FoldersApi


class TestFoldersApi(unittest.TestCase):
    """ FoldersApi unit test stubs """

    def setUp(self):
        self.api = docusign_esign.apis.folders_api.FoldersApi()

    def tearDown(self):
        pass

    def test_list(self):
        """
        Test case for list

        Gets a list of the folders for the account.
        """
        pass

    def test_list_items(self):
        """
        Test case for list_items

        Gets a list of the envelopes in the specified folder.
        """
        pass

    def test_move_envelopes(self):
        """
        Test case for move_envelopes

        Moves an envelope from its current folder to the specified folder.
        """
        pass

    def test_search(self):
        """
        Test case for search

        Gets a list of envelopes in folders matching the specified criteria.
        """
        pass


if __name__ == '__main__':
    unittest.main()
