# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.

    OpenAPI spec version: v2.1
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AccountIdentityInputOption(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, is_required=None, option_name=None, value_type=None):
        """
        AccountIdentityInputOption - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'is_required': 'bool',
            'option_name': 'str',
            'value_type': 'str'
        }

        self.attribute_map = {
            'is_required': 'isRequired',
            'option_name': 'optionName',
            'value_type': 'valueType'
        }

        self._is_required = is_required
        self._option_name = option_name
        self._value_type = value_type

    @property
    def is_required(self):
        """
        Gets the is_required of this AccountIdentityInputOption.
        

        :return: The is_required of this AccountIdentityInputOption.
        :rtype: bool
        """
        return self._is_required

    @is_required.setter
    def is_required(self, is_required):
        """
        Sets the is_required of this AccountIdentityInputOption.
        

        :param is_required: The is_required of this AccountIdentityInputOption.
        :type: bool
        """

        self._is_required = is_required

    @property
    def option_name(self):
        """
        Gets the option_name of this AccountIdentityInputOption.
        

        :return: The option_name of this AccountIdentityInputOption.
        :rtype: str
        """
        return self._option_name

    @option_name.setter
    def option_name(self, option_name):
        """
        Sets the option_name of this AccountIdentityInputOption.
        

        :param option_name: The option_name of this AccountIdentityInputOption.
        :type: str
        """

        self._option_name = option_name

    @property
    def value_type(self):
        """
        Gets the value_type of this AccountIdentityInputOption.
        

        :return: The value_type of this AccountIdentityInputOption.
        :rtype: str
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type):
        """
        Sets the value_type of this AccountIdentityInputOption.
        

        :param value_type: The value_type of this AccountIdentityInputOption.
        :type: str
        """

        self._value_type = value_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
