# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class BillingDiscount(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, begin_quantity=None, discount=None, end_quantity=None):
        """
        BillingDiscount - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'begin_quantity': 'str',
            'discount': 'str',
            'end_quantity': 'str'
        }

        self.attribute_map = {
            'begin_quantity': 'beginQuantity',
            'discount': 'discount',
            'end_quantity': 'endQuantity'
        }

        self._begin_quantity = begin_quantity
        self._discount = discount
        self._end_quantity = end_quantity

    @property
    def begin_quantity(self):
        """
        Gets the begin_quantity of this BillingDiscount.
        Reserved: TBD

        :return: The begin_quantity of this BillingDiscount.
        :rtype: str
        """
        return self._begin_quantity

    @begin_quantity.setter
    def begin_quantity(self, begin_quantity):
        """
        Sets the begin_quantity of this BillingDiscount.
        Reserved: TBD

        :param begin_quantity: The begin_quantity of this BillingDiscount.
        :type: str
        """

        self._begin_quantity = begin_quantity

    @property
    def discount(self):
        """
        Gets the discount of this BillingDiscount.
        

        :return: The discount of this BillingDiscount.
        :rtype: str
        """
        return self._discount

    @discount.setter
    def discount(self, discount):
        """
        Sets the discount of this BillingDiscount.
        

        :param discount: The discount of this BillingDiscount.
        :type: str
        """

        self._discount = discount

    @property
    def end_quantity(self):
        """
        Gets the end_quantity of this BillingDiscount.
        

        :return: The end_quantity of this BillingDiscount.
        :rtype: str
        """
        return self._end_quantity

    @end_quantity.setter
    def end_quantity(self, end_quantity):
        """
        Sets the end_quantity of this BillingDiscount.
        

        :param end_quantity: The end_quantity of this BillingDiscount.
        :type: str
        """

        self._end_quantity = end_quantity

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
