# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BillingPayment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'str',
        'invoice_id': 'str',
        'payment_id': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'invoice_id': 'invoiceId',
        'payment_id': 'paymentId'
    }

    def __init__(self, amount=None, invoice_id=None, payment_id=None):  # noqa: E501
        """BillingPayment - a model defined in Swagger"""  # noqa: E501

        self._amount = None
        self._invoice_id = None
        self._payment_id = None
        self.discriminator = None

        if amount is not None:
            self.amount = amount
        if invoice_id is not None:
            self.invoice_id = invoice_id
        if payment_id is not None:
            self.payment_id = payment_id

    @property
    def amount(self):
        """Gets the amount of this BillingPayment.  # noqa: E501

        Reserved: TBD  # noqa: E501

        :return: The amount of this BillingPayment.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this BillingPayment.

        Reserved: TBD  # noqa: E501

        :param amount: The amount of this BillingPayment.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def invoice_id(self):
        """Gets the invoice_id of this BillingPayment.  # noqa: E501

        Reserved: TBD  # noqa: E501

        :return: The invoice_id of this BillingPayment.  # noqa: E501
        :rtype: str
        """
        return self._invoice_id

    @invoice_id.setter
    def invoice_id(self, invoice_id):
        """Sets the invoice_id of this BillingPayment.

        Reserved: TBD  # noqa: E501

        :param invoice_id: The invoice_id of this BillingPayment.  # noqa: E501
        :type: str
        """

        self._invoice_id = invoice_id

    @property
    def payment_id(self):
        """Gets the payment_id of this BillingPayment.  # noqa: E501

          # noqa: E501

        :return: The payment_id of this BillingPayment.  # noqa: E501
        :rtype: str
        """
        return self._payment_id

    @payment_id.setter
    def payment_id(self, payment_id):
        """Sets the payment_id of this BillingPayment.

          # noqa: E501

        :param payment_id: The payment_id of this BillingPayment.  # noqa: E501
        :type: str
        """

        self._payment_id = payment_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BillingPayment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BillingPayment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
