# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.  # noqa: E501

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ContactPhoneNumber(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'phone_number': 'str',
        'phone_type': 'str'
    }

    attribute_map = {
        'phone_number': 'phoneNumber',
        'phone_type': 'phoneType'
    }

    def __init__(self, phone_number=None, phone_type=None):  # noqa: E501
        """ContactPhoneNumber - a model defined in Swagger"""  # noqa: E501

        self._phone_number = None
        self._phone_type = None
        self.discriminator = None

        if phone_number is not None:
            self.phone_number = phone_number
        if phone_type is not None:
            self.phone_type = phone_type

    @property
    def phone_number(self):
        """Gets the phone_number of this ContactPhoneNumber.  # noqa: E501

          # noqa: E501

        :return: The phone_number of this ContactPhoneNumber.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this ContactPhoneNumber.

          # noqa: E501

        :param phone_number: The phone_number of this ContactPhoneNumber.  # noqa: E501
        :type: str
        """

        self._phone_number = phone_number

    @property
    def phone_type(self):
        """Gets the phone_type of this ContactPhoneNumber.  # noqa: E501

          # noqa: E501

        :return: The phone_type of this ContactPhoneNumber.  # noqa: E501
        :rtype: str
        """
        return self._phone_type

    @phone_type.setter
    def phone_type(self, phone_type):
        """Sets the phone_type of this ContactPhoneNumber.

          # noqa: E501

        :param phone_type: The phone_type of this ContactPhoneNumber.  # noqa: E501
        :type: str
        """

        self._phone_type = phone_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContactPhoneNumber, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactPhoneNumber):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
