# coding: utf-8

"""
    Docusign eSignature REST API

    The Docusign eSignature REST API provides you with a powerful, convenient, and simple Web services API for interacting with Docusign.  # noqa: E501

    OpenAPI spec version: v2.1
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_esign.client.configuration import Configuration


class Country(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'iso_code': 'str',
        'name': 'str',
        'provinces': 'list[Province]',
        'province_validated': 'str'
    }

    attribute_map = {
        'iso_code': 'isoCode',
        'name': 'name',
        'provinces': 'provinces',
        'province_validated': 'provinceValidated'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """Country - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._iso_code = None
        self._name = None
        self._provinces = None
        self._province_validated = None
        self.discriminator = None

        setattr(self, "_{}".format('iso_code'), kwargs.get('iso_code', None))
        setattr(self, "_{}".format('name'), kwargs.get('name', None))
        setattr(self, "_{}".format('provinces'), kwargs.get('provinces', None))
        setattr(self, "_{}".format('province_validated'), kwargs.get('province_validated', None))

    @property
    def iso_code(self):
        """Gets the iso_code of this Country.  # noqa: E501

          # noqa: E501

        :return: The iso_code of this Country.  # noqa: E501
        :rtype: str
        """
        return self._iso_code

    @iso_code.setter
    def iso_code(self, iso_code):
        """Sets the iso_code of this Country.

          # noqa: E501

        :param iso_code: The iso_code of this Country.  # noqa: E501
        :type: str
        """

        self._iso_code = iso_code

    @property
    def name(self):
        """Gets the name of this Country.  # noqa: E501

          # noqa: E501

        :return: The name of this Country.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Country.

          # noqa: E501

        :param name: The name of this Country.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def provinces(self):
        """Gets the provinces of this Country.  # noqa: E501

          # noqa: E501

        :return: The provinces of this Country.  # noqa: E501
        :rtype: list[Province]
        """
        return self._provinces

    @provinces.setter
    def provinces(self, provinces):
        """Sets the provinces of this Country.

          # noqa: E501

        :param provinces: The provinces of this Country.  # noqa: E501
        :type: list[Province]
        """

        self._provinces = provinces

    @property
    def province_validated(self):
        """Gets the province_validated of this Country.  # noqa: E501

          # noqa: E501

        :return: The province_validated of this Country.  # noqa: E501
        :rtype: str
        """
        return self._province_validated

    @province_validated.setter
    def province_validated(self, province_validated):
        """Sets the province_validated of this Country.

          # noqa: E501

        :param province_validated: The province_validated of this Country.  # noqa: E501
        :type: str
        """

        self._province_validated = province_validated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Country, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Country):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Country):
            return True

        return self.to_dict() != other.to_dict()
