# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.  # noqa: E501

    OpenAPI spec version: v2.1
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FavoriteTemplatesContentItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error_details': 'ErrorDetails',
        'favorited_date': 'str',
        'template_id': 'str'
    }

    attribute_map = {
        'error_details': 'errorDetails',
        'favorited_date': 'favoritedDate',
        'template_id': 'templateId'
    }

    def __init__(self, error_details=None, favorited_date=None, template_id=None):  # noqa: E501
        """FavoriteTemplatesContentItem - a model defined in Swagger"""  # noqa: E501

        self._error_details = None
        self._favorited_date = None
        self._template_id = None
        self.discriminator = None

        if error_details is not None:
            self.error_details = error_details
        if favorited_date is not None:
            self.favorited_date = favorited_date
        if template_id is not None:
            self.template_id = template_id

    @property
    def error_details(self):
        """Gets the error_details of this FavoriteTemplatesContentItem.  # noqa: E501


        :return: The error_details of this FavoriteTemplatesContentItem.  # noqa: E501
        :rtype: ErrorDetails
        """
        return self._error_details

    @error_details.setter
    def error_details(self, error_details):
        """Sets the error_details of this FavoriteTemplatesContentItem.


        :param error_details: The error_details of this FavoriteTemplatesContentItem.  # noqa: E501
        :type: ErrorDetails
        """

        self._error_details = error_details

    @property
    def favorited_date(self):
        """Gets the favorited_date of this FavoriteTemplatesContentItem.  # noqa: E501

          # noqa: E501

        :return: The favorited_date of this FavoriteTemplatesContentItem.  # noqa: E501
        :rtype: str
        """
        return self._favorited_date

    @favorited_date.setter
    def favorited_date(self, favorited_date):
        """Sets the favorited_date of this FavoriteTemplatesContentItem.

          # noqa: E501

        :param favorited_date: The favorited_date of this FavoriteTemplatesContentItem.  # noqa: E501
        :type: str
        """

        self._favorited_date = favorited_date

    @property
    def template_id(self):
        """Gets the template_id of this FavoriteTemplatesContentItem.  # noqa: E501

        The unique identifier of the template. If this is not provided, DocuSign will generate a value.   # noqa: E501

        :return: The template_id of this FavoriteTemplatesContentItem.  # noqa: E501
        :rtype: str
        """
        return self._template_id

    @template_id.setter
    def template_id(self, template_id):
        """Sets the template_id of this FavoriteTemplatesContentItem.

        The unique identifier of the template. If this is not provided, DocuSign will generate a value.   # noqa: E501

        :param template_id: The template_id of this FavoriteTemplatesContentItem.  # noqa: E501
        :type: str
        """

        self._template_id = template_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FavoriteTemplatesContentItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FavoriteTemplatesContentItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
