# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PaymentLineItem(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, amount_reference=None, description=None, item_code=None, name=None):
        """
        PaymentLineItem - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'amount_reference': 'str',
            'description': 'str',
            'item_code': 'str',
            'name': 'str'
        }

        self.attribute_map = {
            'amount_reference': 'amountReference',
            'description': 'description',
            'item_code': 'itemCode',
            'name': 'name'
        }

        self._amount_reference = amount_reference
        self._description = description
        self._item_code = item_code
        self._name = name

    @property
    def amount_reference(self):
        """
        Gets the amount_reference of this PaymentLineItem.
        

        :return: The amount_reference of this PaymentLineItem.
        :rtype: str
        """
        return self._amount_reference

    @amount_reference.setter
    def amount_reference(self, amount_reference):
        """
        Sets the amount_reference of this PaymentLineItem.
        

        :param amount_reference: The amount_reference of this PaymentLineItem.
        :type: str
        """

        self._amount_reference = amount_reference

    @property
    def description(self):
        """
        Gets the description of this PaymentLineItem.
        

        :return: The description of this PaymentLineItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this PaymentLineItem.
        

        :param description: The description of this PaymentLineItem.
        :type: str
        """

        self._description = description

    @property
    def item_code(self):
        """
        Gets the item_code of this PaymentLineItem.
        

        :return: The item_code of this PaymentLineItem.
        :rtype: str
        """
        return self._item_code

    @item_code.setter
    def item_code(self, item_code):
        """
        Sets the item_code of this PaymentLineItem.
        

        :param item_code: The item_code of this PaymentLineItem.
        :type: str
        """

        self._item_code = item_code

    @property
    def name(self):
        """
        Gets the name of this PaymentLineItem.
        

        :return: The name of this PaymentLineItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PaymentLineItem.
        

        :param name: The name of this PaymentLineItem.
        :type: str
        """

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
