# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RecipientSignatureInformation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, font_style=None, signature_initials=None, signature_name=None):
        """
        RecipientSignatureInformation - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'font_style': 'str',
            'signature_initials': 'str',
            'signature_name': 'str'
        }

        self.attribute_map = {
            'font_style': 'fontStyle',
            'signature_initials': 'signatureInitials',
            'signature_name': 'signatureName'
        }

        self._font_style = font_style
        self._signature_initials = signature_initials
        self._signature_name = signature_name

    @property
    def font_style(self):
        """
        Gets the font_style of this RecipientSignatureInformation.
        

        :return: The font_style of this RecipientSignatureInformation.
        :rtype: str
        """
        return self._font_style

    @font_style.setter
    def font_style(self, font_style):
        """
        Sets the font_style of this RecipientSignatureInformation.
        

        :param font_style: The font_style of this RecipientSignatureInformation.
        :type: str
        """

        self._font_style = font_style

    @property
    def signature_initials(self):
        """
        Gets the signature_initials of this RecipientSignatureInformation.
        

        :return: The signature_initials of this RecipientSignatureInformation.
        :rtype: str
        """
        return self._signature_initials

    @signature_initials.setter
    def signature_initials(self, signature_initials):
        """
        Sets the signature_initials of this RecipientSignatureInformation.
        

        :param signature_initials: The signature_initials of this RecipientSignatureInformation.
        :type: str
        """

        self._signature_initials = signature_initials

    @property
    def signature_name(self):
        """
        Gets the signature_name of this RecipientSignatureInformation.
        Specifies the user signature name.

        :return: The signature_name of this RecipientSignatureInformation.
        :rtype: str
        """
        return self._signature_name

    @signature_name.setter
    def signature_name(self, signature_name):
        """
        Sets the signature_name of this RecipientSignatureInformation.
        Specifies the user signature name.

        :param signature_name: The signature_name of this RecipientSignatureInformation.
        :type: str
        """

        self._signature_name = signature_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
