# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.  # noqa: E501

    OpenAPI spec version: v2.1
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ReportInProductGet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authentication_success_filter': 'str',
        'custom_field_filter': 'str',
        'date_range_custom_from_date': 'str',
        'date_range_custom_to_date': 'str',
        'date_range_filter': 'str',
        'display_order': 'str',
        'envelope_date_type_filter': 'str',
        'envelope_recipient_name_contains_filter': 'str',
        'envelope_status_filter': 'str',
        'envelope_subject_contains_filter': 'str',
        'fields': 'list[ReportInProductField]',
        'last_scheduled_execution_date': 'str',
        'last_scheduled_execution_success_date': 'str',
        'max_download_rows': 'str',
        'max_grid_rows': 'str',
        'max_scheduled_rows': 'str',
        'period_length_filter': 'str',
        'report_customized_id': 'str',
        'report_description': 'str',
        'report_id': 'str',
        'report_name': 'str',
        'report_type': 'str',
        'run_uri': 'str',
        'save_uri': 'str',
        'schedule_id': 'str',
        'sent_by_details': 'ReportInProductSentByDetails',
        'sent_by_filter': 'str',
        'sent_by_ids': 'str',
        'sort_field_direction': 'str',
        'sort_field_name': 'str',
        'verification_status_filter': 'str'
    }

    attribute_map = {
        'authentication_success_filter': 'authenticationSuccessFilter',
        'custom_field_filter': 'customFieldFilter',
        'date_range_custom_from_date': 'dateRangeCustomFromDate',
        'date_range_custom_to_date': 'dateRangeCustomToDate',
        'date_range_filter': 'dateRangeFilter',
        'display_order': 'displayOrder',
        'envelope_date_type_filter': 'envelopeDateTypeFilter',
        'envelope_recipient_name_contains_filter': 'envelopeRecipientNameContainsFilter',
        'envelope_status_filter': 'envelopeStatusFilter',
        'envelope_subject_contains_filter': 'envelopeSubjectContainsFilter',
        'fields': 'fields',
        'last_scheduled_execution_date': 'lastScheduledExecutionDate',
        'last_scheduled_execution_success_date': 'lastScheduledExecutionSuccessDate',
        'max_download_rows': 'maxDownloadRows',
        'max_grid_rows': 'maxGridRows',
        'max_scheduled_rows': 'maxScheduledRows',
        'period_length_filter': 'periodLengthFilter',
        'report_customized_id': 'reportCustomizedId',
        'report_description': 'reportDescription',
        'report_id': 'reportId',
        'report_name': 'reportName',
        'report_type': 'reportType',
        'run_uri': 'runUri',
        'save_uri': 'saveUri',
        'schedule_id': 'scheduleId',
        'sent_by_details': 'sentByDetails',
        'sent_by_filter': 'sentByFilter',
        'sent_by_ids': 'sentByIds',
        'sort_field_direction': 'sortFieldDirection',
        'sort_field_name': 'sortFieldName',
        'verification_status_filter': 'verificationStatusFilter'
    }

    def __init__(self, authentication_success_filter=None, custom_field_filter=None, date_range_custom_from_date=None, date_range_custom_to_date=None, date_range_filter=None, display_order=None, envelope_date_type_filter=None, envelope_recipient_name_contains_filter=None, envelope_status_filter=None, envelope_subject_contains_filter=None, fields=None, last_scheduled_execution_date=None, last_scheduled_execution_success_date=None, max_download_rows=None, max_grid_rows=None, max_scheduled_rows=None, period_length_filter=None, report_customized_id=None, report_description=None, report_id=None, report_name=None, report_type=None, run_uri=None, save_uri=None, schedule_id=None, sent_by_details=None, sent_by_filter=None, sent_by_ids=None, sort_field_direction=None, sort_field_name=None, verification_status_filter=None):  # noqa: E501
        """ReportInProductGet - a model defined in Swagger"""  # noqa: E501

        self._authentication_success_filter = None
        self._custom_field_filter = None
        self._date_range_custom_from_date = None
        self._date_range_custom_to_date = None
        self._date_range_filter = None
        self._display_order = None
        self._envelope_date_type_filter = None
        self._envelope_recipient_name_contains_filter = None
        self._envelope_status_filter = None
        self._envelope_subject_contains_filter = None
        self._fields = None
        self._last_scheduled_execution_date = None
        self._last_scheduled_execution_success_date = None
        self._max_download_rows = None
        self._max_grid_rows = None
        self._max_scheduled_rows = None
        self._period_length_filter = None
        self._report_customized_id = None
        self._report_description = None
        self._report_id = None
        self._report_name = None
        self._report_type = None
        self._run_uri = None
        self._save_uri = None
        self._schedule_id = None
        self._sent_by_details = None
        self._sent_by_filter = None
        self._sent_by_ids = None
        self._sort_field_direction = None
        self._sort_field_name = None
        self._verification_status_filter = None
        self.discriminator = None

        if authentication_success_filter is not None:
            self.authentication_success_filter = authentication_success_filter
        if custom_field_filter is not None:
            self.custom_field_filter = custom_field_filter
        if date_range_custom_from_date is not None:
            self.date_range_custom_from_date = date_range_custom_from_date
        if date_range_custom_to_date is not None:
            self.date_range_custom_to_date = date_range_custom_to_date
        if date_range_filter is not None:
            self.date_range_filter = date_range_filter
        if display_order is not None:
            self.display_order = display_order
        if envelope_date_type_filter is not None:
            self.envelope_date_type_filter = envelope_date_type_filter
        if envelope_recipient_name_contains_filter is not None:
            self.envelope_recipient_name_contains_filter = envelope_recipient_name_contains_filter
        if envelope_status_filter is not None:
            self.envelope_status_filter = envelope_status_filter
        if envelope_subject_contains_filter is not None:
            self.envelope_subject_contains_filter = envelope_subject_contains_filter
        if fields is not None:
            self.fields = fields
        if last_scheduled_execution_date is not None:
            self.last_scheduled_execution_date = last_scheduled_execution_date
        if last_scheduled_execution_success_date is not None:
            self.last_scheduled_execution_success_date = last_scheduled_execution_success_date
        if max_download_rows is not None:
            self.max_download_rows = max_download_rows
        if max_grid_rows is not None:
            self.max_grid_rows = max_grid_rows
        if max_scheduled_rows is not None:
            self.max_scheduled_rows = max_scheduled_rows
        if period_length_filter is not None:
            self.period_length_filter = period_length_filter
        if report_customized_id is not None:
            self.report_customized_id = report_customized_id
        if report_description is not None:
            self.report_description = report_description
        if report_id is not None:
            self.report_id = report_id
        if report_name is not None:
            self.report_name = report_name
        if report_type is not None:
            self.report_type = report_type
        if run_uri is not None:
            self.run_uri = run_uri
        if save_uri is not None:
            self.save_uri = save_uri
        if schedule_id is not None:
            self.schedule_id = schedule_id
        if sent_by_details is not None:
            self.sent_by_details = sent_by_details
        if sent_by_filter is not None:
            self.sent_by_filter = sent_by_filter
        if sent_by_ids is not None:
            self.sent_by_ids = sent_by_ids
        if sort_field_direction is not None:
            self.sort_field_direction = sort_field_direction
        if sort_field_name is not None:
            self.sort_field_name = sort_field_name
        if verification_status_filter is not None:
            self.verification_status_filter = verification_status_filter

    @property
    def authentication_success_filter(self):
        """Gets the authentication_success_filter of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The authentication_success_filter of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._authentication_success_filter

    @authentication_success_filter.setter
    def authentication_success_filter(self, authentication_success_filter):
        """Sets the authentication_success_filter of this ReportInProductGet.

          # noqa: E501

        :param authentication_success_filter: The authentication_success_filter of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._authentication_success_filter = authentication_success_filter

    @property
    def custom_field_filter(self):
        """Gets the custom_field_filter of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The custom_field_filter of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._custom_field_filter

    @custom_field_filter.setter
    def custom_field_filter(self, custom_field_filter):
        """Sets the custom_field_filter of this ReportInProductGet.

          # noqa: E501

        :param custom_field_filter: The custom_field_filter of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._custom_field_filter = custom_field_filter

    @property
    def date_range_custom_from_date(self):
        """Gets the date_range_custom_from_date of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The date_range_custom_from_date of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._date_range_custom_from_date

    @date_range_custom_from_date.setter
    def date_range_custom_from_date(self, date_range_custom_from_date):
        """Sets the date_range_custom_from_date of this ReportInProductGet.

          # noqa: E501

        :param date_range_custom_from_date: The date_range_custom_from_date of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._date_range_custom_from_date = date_range_custom_from_date

    @property
    def date_range_custom_to_date(self):
        """Gets the date_range_custom_to_date of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The date_range_custom_to_date of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._date_range_custom_to_date

    @date_range_custom_to_date.setter
    def date_range_custom_to_date(self, date_range_custom_to_date):
        """Sets the date_range_custom_to_date of this ReportInProductGet.

          # noqa: E501

        :param date_range_custom_to_date: The date_range_custom_to_date of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._date_range_custom_to_date = date_range_custom_to_date

    @property
    def date_range_filter(self):
        """Gets the date_range_filter of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The date_range_filter of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._date_range_filter

    @date_range_filter.setter
    def date_range_filter(self, date_range_filter):
        """Sets the date_range_filter of this ReportInProductGet.

          # noqa: E501

        :param date_range_filter: The date_range_filter of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._date_range_filter = date_range_filter

    @property
    def display_order(self):
        """Gets the display_order of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The display_order of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._display_order

    @display_order.setter
    def display_order(self, display_order):
        """Sets the display_order of this ReportInProductGet.

          # noqa: E501

        :param display_order: The display_order of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._display_order = display_order

    @property
    def envelope_date_type_filter(self):
        """Gets the envelope_date_type_filter of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The envelope_date_type_filter of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._envelope_date_type_filter

    @envelope_date_type_filter.setter
    def envelope_date_type_filter(self, envelope_date_type_filter):
        """Sets the envelope_date_type_filter of this ReportInProductGet.

          # noqa: E501

        :param envelope_date_type_filter: The envelope_date_type_filter of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._envelope_date_type_filter = envelope_date_type_filter

    @property
    def envelope_recipient_name_contains_filter(self):
        """Gets the envelope_recipient_name_contains_filter of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The envelope_recipient_name_contains_filter of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._envelope_recipient_name_contains_filter

    @envelope_recipient_name_contains_filter.setter
    def envelope_recipient_name_contains_filter(self, envelope_recipient_name_contains_filter):
        """Sets the envelope_recipient_name_contains_filter of this ReportInProductGet.

          # noqa: E501

        :param envelope_recipient_name_contains_filter: The envelope_recipient_name_contains_filter of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._envelope_recipient_name_contains_filter = envelope_recipient_name_contains_filter

    @property
    def envelope_status_filter(self):
        """Gets the envelope_status_filter of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The envelope_status_filter of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._envelope_status_filter

    @envelope_status_filter.setter
    def envelope_status_filter(self, envelope_status_filter):
        """Sets the envelope_status_filter of this ReportInProductGet.

          # noqa: E501

        :param envelope_status_filter: The envelope_status_filter of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._envelope_status_filter = envelope_status_filter

    @property
    def envelope_subject_contains_filter(self):
        """Gets the envelope_subject_contains_filter of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The envelope_subject_contains_filter of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._envelope_subject_contains_filter

    @envelope_subject_contains_filter.setter
    def envelope_subject_contains_filter(self, envelope_subject_contains_filter):
        """Sets the envelope_subject_contains_filter of this ReportInProductGet.

          # noqa: E501

        :param envelope_subject_contains_filter: The envelope_subject_contains_filter of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._envelope_subject_contains_filter = envelope_subject_contains_filter

    @property
    def fields(self):
        """Gets the fields of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The fields of this ReportInProductGet.  # noqa: E501
        :rtype: list[ReportInProductField]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this ReportInProductGet.

          # noqa: E501

        :param fields: The fields of this ReportInProductGet.  # noqa: E501
        :type: list[ReportInProductField]
        """

        self._fields = fields

    @property
    def last_scheduled_execution_date(self):
        """Gets the last_scheduled_execution_date of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The last_scheduled_execution_date of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._last_scheduled_execution_date

    @last_scheduled_execution_date.setter
    def last_scheduled_execution_date(self, last_scheduled_execution_date):
        """Sets the last_scheduled_execution_date of this ReportInProductGet.

          # noqa: E501

        :param last_scheduled_execution_date: The last_scheduled_execution_date of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._last_scheduled_execution_date = last_scheduled_execution_date

    @property
    def last_scheduled_execution_success_date(self):
        """Gets the last_scheduled_execution_success_date of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The last_scheduled_execution_success_date of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._last_scheduled_execution_success_date

    @last_scheduled_execution_success_date.setter
    def last_scheduled_execution_success_date(self, last_scheduled_execution_success_date):
        """Sets the last_scheduled_execution_success_date of this ReportInProductGet.

          # noqa: E501

        :param last_scheduled_execution_success_date: The last_scheduled_execution_success_date of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._last_scheduled_execution_success_date = last_scheduled_execution_success_date

    @property
    def max_download_rows(self):
        """Gets the max_download_rows of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The max_download_rows of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._max_download_rows

    @max_download_rows.setter
    def max_download_rows(self, max_download_rows):
        """Sets the max_download_rows of this ReportInProductGet.

          # noqa: E501

        :param max_download_rows: The max_download_rows of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._max_download_rows = max_download_rows

    @property
    def max_grid_rows(self):
        """Gets the max_grid_rows of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The max_grid_rows of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._max_grid_rows

    @max_grid_rows.setter
    def max_grid_rows(self, max_grid_rows):
        """Sets the max_grid_rows of this ReportInProductGet.

          # noqa: E501

        :param max_grid_rows: The max_grid_rows of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._max_grid_rows = max_grid_rows

    @property
    def max_scheduled_rows(self):
        """Gets the max_scheduled_rows of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The max_scheduled_rows of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._max_scheduled_rows

    @max_scheduled_rows.setter
    def max_scheduled_rows(self, max_scheduled_rows):
        """Sets the max_scheduled_rows of this ReportInProductGet.

          # noqa: E501

        :param max_scheduled_rows: The max_scheduled_rows of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._max_scheduled_rows = max_scheduled_rows

    @property
    def period_length_filter(self):
        """Gets the period_length_filter of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The period_length_filter of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._period_length_filter

    @period_length_filter.setter
    def period_length_filter(self, period_length_filter):
        """Sets the period_length_filter of this ReportInProductGet.

          # noqa: E501

        :param period_length_filter: The period_length_filter of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._period_length_filter = period_length_filter

    @property
    def report_customized_id(self):
        """Gets the report_customized_id of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The report_customized_id of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._report_customized_id

    @report_customized_id.setter
    def report_customized_id(self, report_customized_id):
        """Sets the report_customized_id of this ReportInProductGet.

          # noqa: E501

        :param report_customized_id: The report_customized_id of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._report_customized_id = report_customized_id

    @property
    def report_description(self):
        """Gets the report_description of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The report_description of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._report_description

    @report_description.setter
    def report_description(self, report_description):
        """Sets the report_description of this ReportInProductGet.

          # noqa: E501

        :param report_description: The report_description of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._report_description = report_description

    @property
    def report_id(self):
        """Gets the report_id of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The report_id of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._report_id

    @report_id.setter
    def report_id(self, report_id):
        """Sets the report_id of this ReportInProductGet.

          # noqa: E501

        :param report_id: The report_id of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._report_id = report_id

    @property
    def report_name(self):
        """Gets the report_name of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The report_name of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._report_name

    @report_name.setter
    def report_name(self, report_name):
        """Sets the report_name of this ReportInProductGet.

          # noqa: E501

        :param report_name: The report_name of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._report_name = report_name

    @property
    def report_type(self):
        """Gets the report_type of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The report_type of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._report_type

    @report_type.setter
    def report_type(self, report_type):
        """Sets the report_type of this ReportInProductGet.

          # noqa: E501

        :param report_type: The report_type of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._report_type = report_type

    @property
    def run_uri(self):
        """Gets the run_uri of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The run_uri of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._run_uri

    @run_uri.setter
    def run_uri(self, run_uri):
        """Sets the run_uri of this ReportInProductGet.

          # noqa: E501

        :param run_uri: The run_uri of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._run_uri = run_uri

    @property
    def save_uri(self):
        """Gets the save_uri of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The save_uri of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._save_uri

    @save_uri.setter
    def save_uri(self, save_uri):
        """Sets the save_uri of this ReportInProductGet.

          # noqa: E501

        :param save_uri: The save_uri of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._save_uri = save_uri

    @property
    def schedule_id(self):
        """Gets the schedule_id of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The schedule_id of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._schedule_id

    @schedule_id.setter
    def schedule_id(self, schedule_id):
        """Sets the schedule_id of this ReportInProductGet.

          # noqa: E501

        :param schedule_id: The schedule_id of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._schedule_id = schedule_id

    @property
    def sent_by_details(self):
        """Gets the sent_by_details of this ReportInProductGet.  # noqa: E501


        :return: The sent_by_details of this ReportInProductGet.  # noqa: E501
        :rtype: ReportInProductSentByDetails
        """
        return self._sent_by_details

    @sent_by_details.setter
    def sent_by_details(self, sent_by_details):
        """Sets the sent_by_details of this ReportInProductGet.


        :param sent_by_details: The sent_by_details of this ReportInProductGet.  # noqa: E501
        :type: ReportInProductSentByDetails
        """

        self._sent_by_details = sent_by_details

    @property
    def sent_by_filter(self):
        """Gets the sent_by_filter of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The sent_by_filter of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._sent_by_filter

    @sent_by_filter.setter
    def sent_by_filter(self, sent_by_filter):
        """Sets the sent_by_filter of this ReportInProductGet.

          # noqa: E501

        :param sent_by_filter: The sent_by_filter of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._sent_by_filter = sent_by_filter

    @property
    def sent_by_ids(self):
        """Gets the sent_by_ids of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The sent_by_ids of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._sent_by_ids

    @sent_by_ids.setter
    def sent_by_ids(self, sent_by_ids):
        """Sets the sent_by_ids of this ReportInProductGet.

          # noqa: E501

        :param sent_by_ids: The sent_by_ids of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._sent_by_ids = sent_by_ids

    @property
    def sort_field_direction(self):
        """Gets the sort_field_direction of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The sort_field_direction of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._sort_field_direction

    @sort_field_direction.setter
    def sort_field_direction(self, sort_field_direction):
        """Sets the sort_field_direction of this ReportInProductGet.

          # noqa: E501

        :param sort_field_direction: The sort_field_direction of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._sort_field_direction = sort_field_direction

    @property
    def sort_field_name(self):
        """Gets the sort_field_name of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The sort_field_name of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._sort_field_name

    @sort_field_name.setter
    def sort_field_name(self, sort_field_name):
        """Sets the sort_field_name of this ReportInProductGet.

          # noqa: E501

        :param sort_field_name: The sort_field_name of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._sort_field_name = sort_field_name

    @property
    def verification_status_filter(self):
        """Gets the verification_status_filter of this ReportInProductGet.  # noqa: E501

          # noqa: E501

        :return: The verification_status_filter of this ReportInProductGet.  # noqa: E501
        :rtype: str
        """
        return self._verification_status_filter

    @verification_status_filter.setter
    def verification_status_filter(self, verification_status_filter):
        """Sets the verification_status_filter of this ReportInProductGet.

          # noqa: E501

        :param verification_status_filter: The verification_status_filter of this ReportInProductGet.  # noqa: E501
        :type: str
        """

        self._verification_status_filter = verification_status_filter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReportInProductGet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportInProductGet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
