# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.  # noqa: E501

    OpenAPI spec version: v2.1
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_esign.client.configuration import Configuration


class ReportInProductRunResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'end_position': 'str',
        'exceeded_max_results': 'str',
        'last_warehouse_refresh_date_time': 'str',
        'result_set_size': 'str',
        'rows': 'list[ReportInProductRunResponseRow]',
        'start_position': 'str',
        'total_set_size': 'str'
    }

    attribute_map = {
        'end_position': 'endPosition',
        'exceeded_max_results': 'exceededMaxResults',
        'last_warehouse_refresh_date_time': 'lastWarehouseRefreshDateTime',
        'result_set_size': 'resultSetSize',
        'rows': 'rows',
        'start_position': 'startPosition',
        'total_set_size': 'totalSetSize'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """ReportInProductRunResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._end_position = None
        self._exceeded_max_results = None
        self._last_warehouse_refresh_date_time = None
        self._result_set_size = None
        self._rows = None
        self._start_position = None
        self._total_set_size = None
        self.discriminator = None

        setattr(self, "_{}".format('end_position'), kwargs.get('end_position', None))
        setattr(self, "_{}".format('exceeded_max_results'), kwargs.get('exceeded_max_results', None))
        setattr(self, "_{}".format('last_warehouse_refresh_date_time'), kwargs.get('last_warehouse_refresh_date_time', None))
        setattr(self, "_{}".format('result_set_size'), kwargs.get('result_set_size', None))
        setattr(self, "_{}".format('rows'), kwargs.get('rows', None))
        setattr(self, "_{}".format('start_position'), kwargs.get('start_position', None))
        setattr(self, "_{}".format('total_set_size'), kwargs.get('total_set_size', None))

    @property
    def end_position(self):
        """Gets the end_position of this ReportInProductRunResponse.  # noqa: E501

        The last position in the result set.   # noqa: E501

        :return: The end_position of this ReportInProductRunResponse.  # noqa: E501
        :rtype: str
        """
        return self._end_position

    @end_position.setter
    def end_position(self, end_position):
        """Sets the end_position of this ReportInProductRunResponse.

        The last position in the result set.   # noqa: E501

        :param end_position: The end_position of this ReportInProductRunResponse.  # noqa: E501
        :type: str
        """

        self._end_position = end_position

    @property
    def exceeded_max_results(self):
        """Gets the exceeded_max_results of this ReportInProductRunResponse.  # noqa: E501

          # noqa: E501

        :return: The exceeded_max_results of this ReportInProductRunResponse.  # noqa: E501
        :rtype: str
        """
        return self._exceeded_max_results

    @exceeded_max_results.setter
    def exceeded_max_results(self, exceeded_max_results):
        """Sets the exceeded_max_results of this ReportInProductRunResponse.

          # noqa: E501

        :param exceeded_max_results: The exceeded_max_results of this ReportInProductRunResponse.  # noqa: E501
        :type: str
        """

        self._exceeded_max_results = exceeded_max_results

    @property
    def last_warehouse_refresh_date_time(self):
        """Gets the last_warehouse_refresh_date_time of this ReportInProductRunResponse.  # noqa: E501

          # noqa: E501

        :return: The last_warehouse_refresh_date_time of this ReportInProductRunResponse.  # noqa: E501
        :rtype: str
        """
        return self._last_warehouse_refresh_date_time

    @last_warehouse_refresh_date_time.setter
    def last_warehouse_refresh_date_time(self, last_warehouse_refresh_date_time):
        """Sets the last_warehouse_refresh_date_time of this ReportInProductRunResponse.

          # noqa: E501

        :param last_warehouse_refresh_date_time: The last_warehouse_refresh_date_time of this ReportInProductRunResponse.  # noqa: E501
        :type: str
        """

        self._last_warehouse_refresh_date_time = last_warehouse_refresh_date_time

    @property
    def result_set_size(self):
        """Gets the result_set_size of this ReportInProductRunResponse.  # noqa: E501

        The number of results returned in this response.   # noqa: E501

        :return: The result_set_size of this ReportInProductRunResponse.  # noqa: E501
        :rtype: str
        """
        return self._result_set_size

    @result_set_size.setter
    def result_set_size(self, result_set_size):
        """Sets the result_set_size of this ReportInProductRunResponse.

        The number of results returned in this response.   # noqa: E501

        :param result_set_size: The result_set_size of this ReportInProductRunResponse.  # noqa: E501
        :type: str
        """

        self._result_set_size = result_set_size

    @property
    def rows(self):
        """Gets the rows of this ReportInProductRunResponse.  # noqa: E501

          # noqa: E501

        :return: The rows of this ReportInProductRunResponse.  # noqa: E501
        :rtype: list[ReportInProductRunResponseRow]
        """
        return self._rows

    @rows.setter
    def rows(self, rows):
        """Sets the rows of this ReportInProductRunResponse.

          # noqa: E501

        :param rows: The rows of this ReportInProductRunResponse.  # noqa: E501
        :type: list[ReportInProductRunResponseRow]
        """

        self._rows = rows

    @property
    def start_position(self):
        """Gets the start_position of this ReportInProductRunResponse.  # noqa: E501

        Starting position of the current result set.  # noqa: E501

        :return: The start_position of this ReportInProductRunResponse.  # noqa: E501
        :rtype: str
        """
        return self._start_position

    @start_position.setter
    def start_position(self, start_position):
        """Sets the start_position of this ReportInProductRunResponse.

        Starting position of the current result set.  # noqa: E501

        :param start_position: The start_position of this ReportInProductRunResponse.  # noqa: E501
        :type: str
        """

        self._start_position = start_position

    @property
    def total_set_size(self):
        """Gets the total_set_size of this ReportInProductRunResponse.  # noqa: E501

        The total number of items available in the result set. This will always be greater than or equal to the value of the property returning the results in the in the response.  # noqa: E501

        :return: The total_set_size of this ReportInProductRunResponse.  # noqa: E501
        :rtype: str
        """
        return self._total_set_size

    @total_set_size.setter
    def total_set_size(self, total_set_size):
        """Sets the total_set_size of this ReportInProductRunResponse.

        The total number of items available in the result set. This will always be greater than or equal to the value of the property returning the results in the in the response.  # noqa: E501

        :param total_set_size: The total_set_size of this ReportInProductRunResponse.  # noqa: E501
        :type: str
        """

        self._total_set_size = total_set_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReportInProductRunResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportInProductRunResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReportInProductRunResponse):
            return True

        return self.to_dict() != other.to_dict()
