# coding: utf-8

"""
    DocuSign REST API

    The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.

    OpenAPI spec version: v2
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Seal(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, configuration=None, seal_identifier=None):
        """
        Seal - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'configuration': 'dict(str, str)',
            'seal_identifier': 'str'
        }

        self.attribute_map = {
            'configuration': 'configuration',
            'seal_identifier': 'sealIdentifier'
        }

        self._configuration = configuration
        self._seal_identifier = seal_identifier

    @property
    def configuration(self):
        """
        Gets the configuration of this Seal.
        

        :return: The configuration of this Seal.
        :rtype: dict(str, str)
        """
        return self._configuration

    @configuration.setter
    def configuration(self, configuration):
        """
        Sets the configuration of this Seal.
        

        :param configuration: The configuration of this Seal.
        :type: dict(str, str)
        """

        self._configuration = configuration

    @property
    def seal_identifier(self):
        """
        Gets the seal_identifier of this Seal.
        

        :return: The seal_identifier of this Seal.
        :rtype: str
        """
        return self._seal_identifier

    @seal_identifier.setter
    def seal_identifier(self, seal_identifier):
        """
        Sets the seal_identifier of this Seal.
        

        :param seal_identifier: The seal_identifier of this Seal.
        :type: str
        """

        self._seal_identifier = seal_identifier

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
